/**
 * The Rust fixture (docs/plans/2026-10-08-language-coverage.plan.md Task B5.1): a two-member cargo
 * workspace in `ws/`, and `detached/x.rs` under the same open folder with no Cargo.toml above it.
 */
import { spawnSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** `util::greet("x")` in ws/app/src/main.rs, 0-based for `lsp:request`. */
export const RS_GREET_CALL = {
  line: 1,
  character: '    println!("{}", util::'.length,
};

const LOCKFILE = [
  '# This file is automatically @generated by Cargo.',
  '# It is not intended for manual editing.',
  'version = 3',
  '',
  '[[package]]',
  'name = "app"',
  'version = "0.1.0"',
  'dependencies = [',
  ' "util",',
  ']',
  '',
  '[[package]]',
  'name = "util"',
  'version = "0.1.0"',
  '',
].join('\n');

export function writeRustFixture(dir) {
  const ws = join(dir, 'ws');
  mkdirSync(join(ws, 'app', 'src'), { recursive: true });
  mkdirSync(join(ws, 'util', 'src'), { recursive: true });
  mkdirSync(join(dir, 'detached'), { recursive: true });
  writeFileSync(join(ws, 'Cargo.toml'), '[workspace]\nmembers = ["app", "util"]\nresolver = "2"\n');
  writeFileSync(
    join(ws, 'app', 'Cargo.toml'),
    '[package]\nname = "app"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\nutil = { path = "../util" }\n',
  );
  writeFileSync(
    join(ws, 'app', 'src', 'main.rs'),
    'fn main() {\n    println!("{}", util::greet("x"));\n}\n',
  );
  writeFileSync(
    join(ws, 'util', 'Cargo.toml'),
    '[package]\nname = "util"\nversion = "0.1.0"\nedition = "2021"\n',
  );
  writeFileSync(
    join(ws, 'util', 'src', 'lib.rs'),
    '/// Says hi.\npub fn greet(name: &str) -> String {\n    format!("hi {name}")\n}\n',
  );
  const generated = spawnSync('cargo', ['generate-lockfile', '--offline'], {
    cwd: ws,
    stdio: 'ignore',
    timeout: 60_000,
    windowsHide: true,
  });
  if (generated.status !== 0) writeFileSync(join(ws, 'Cargo.lock'), LOCKFILE);
  writeFileSync(join(dir, 'detached', 'x.rs'), 'fn lonely() {}\n\nfn main() {\n    lonely();\n}\n');
  return {
    ws,
    main: join(ws, 'app', 'src', 'main.rs'),
    lib: join(ws, 'util', 'src', 'lib.rs'),
    detached: join(dir, 'detached', 'x.rs'),
  };
}
